### PR TITLE
Document our new workflow

### PR DESCRIPTION
**Pull request by jasonkuhrt**
This is a proposal for our new format. Everyone interested please review. Any objections? This isn't set in stone, just a next step in our evolving study group.

Cheers!

### CODE REVIEW

**Comment by jasonkuhrt** [comment]
@neongreen This will need an explicit passing review to merge now : )

**Review by neongreen — CHANGES_REQUESTED** [review]
It'd be nice to change the instruction to provide an example.

“All solutions to exercises should be placed into corresponding folders. For instance, if your Github nick is `john` and you're solving task `table` from week 3, create a branch called `table/john` and put your solution into `week3/table/john`:

```
$ git checkout -b table/john
$ mkdir week3/table/john
```

When you want feedback on your code (or when you're ready to submit it), create a pull request. Then someone will review it and either suggest improvements or merge it; from then on you'll be able to make fixes to your code in the `master` branch, if needed.”

blah blah

**Comment by jasonkuhrt** [comment]
@neongreen I integrated most of your suggestion. Let me know if that is what you expected. I also simplified/condensed the steps.

Question about:

> Then someone will review it and either suggest improvements or merge it

So when you review a solution, and you fully approve, you will merge it on their behalf? Just confirming that's the workflow you want, then I'll update the steps to state this.

--edit 

Done

**Comment by jasonkuhrt** [comment]
> create a branch called table/john and put your solution into week3/table/john

@neongreen One downside of this is that we now maintain two conventions instead of one. If we agree this is undesirable my proposed solutions would be eitheror:
1. Revert the `week{n}` folder name-spacing
2. Match branch naming with folder naming

Nay/yay?

**Comment by neongreen** [comment]
> we now maintain two conventions instead of one

I think this isn't bad. The `weekN` convention is for browsing convenience; the list of branches is unlikely to be browsed.

**Comment by jasonkuhrt** [comment]
@neongreen Should be good now?

**Comment by neongreen** [comment]
> So when you review a solution, and you fully approve, you will merge it on their behalf? Just confirming that's the workflow you want, then I'll update the steps to state this.

Sorry, haven't noticed this!

No, I think authors should do the merge by themselves.

**Review by neongreen — APPROVED** [review]

**Comment by neongreen** [comment]
So, revert the last commit and after that you can merge it.

**Pull request merged**
